import {staticFile} from 'remotion';
import ledgerJson from './ledger.json';

/**
 * The asset ledger is generated by the inventory pass and is the auditable
 * record behind the compulsory-coverage requirement.
 *
 * 169 raw media filenames in the repository
 *   -> 27 exact-duplicate groups + 6 perceptual near-duplicate groups merged
 *   -> 134 DISTINCT assets (132 image clusters + 2 video clips)
 *   -> minus the 3 logo files (TASCAM / Shivansh Electronics / Dante), which
 *      are excluded from reel content by design
 *   == 131 coverage-relevant assets, split 74 / 30 / 27 across Parts 1-3.
 *
 * `part: 0` marks the three excluded logos; they carry no slug and are never
 * copied into public/img, so they cannot accidentally appear in a reel.
 */
export type LedgerEntry = {
  id: number;
  slug: string | null;
  part: number;
  source: string;
  merged: string[];
  nRaw: number;
  kind: 'image' | 'video' | 'logo';
};

export const LEDGER = ledgerJson as LedgerEntry[];

const BY_ID = new Map<number, LedgerEntry>(LEDGER.map((e) => [e.id, e]));

/** Asset id -> static URL. Throws on a logo or an unknown id. */
export const A = (id: number): string => {
  const e = BY_ID.get(id);
  if (!e) throw new Error(`asset ${id} is not in the ledger`);
  if (!e.slug) throw new Error(`asset ${id} is an excluded logo and must not be used in a reel`);
  return staticFile(`img/${e.slug}`);
};

export const isVideo = (id: number): boolean => BY_ID.get(id)?.kind === 'video';

export const idsForPart = (part: number): number[] =>
  LEDGER.filter((e) => e.part === part).map((e) => e.id);
